[package]
name = "runtime"
version = "0.1.0"
authors = ["cjb <cjb>"]


[build-dependencies]
cc = "1.0"


[dependencies]
board_misoc = { path = "../libboard_misoc"}
ksupport = { path = "../libksupport"}
volatile_cell = "*"


[lib]
path="main.rs"
name = "runtime"
crate-type = ["staticlib"]
